### ISSUE TITLE
The chances of this going the right way...

### ISSUE THREAD

**Issue by brandonros** [alignace/card-reader-phonegap#2]
`CardRader` instead of `CardReader`. Here goes nothing!

**Comment by brandonros** [comment]
```
➜  cordova git:(master) cordova plugin add https://github.com/alignace/card-reader-phonegap.git
Fetching plugin "https://github.com/alignace/card-reader-phonegap.git" via git clone
Repository "https://github.com/alignace/card-reader-phonegap.git" checked out to git ref "master".
Installing "com.alignace.cordova.plugin.card.reader" for ios
Error during processing of action! Attempting to revert...
Failed to install 'com.alignace.cordova.plugin.card.reader':Error: Uh oh!
"/Users/Marketing/Desktop/foo/foo/mobile_apps/ios_app/foo/cordova/plugins/com.alignace.cordova.plugin.card.reader/src/ios/CardRaderPlugin.h" not found!
    at Object.module.exports.common.copyFile (/Users/Marketing/.nvm/versions/node/v5.1.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/common.js:38:40)
    at Object.module.exports.common.copyNewFile (/Users/Marketing/.nvm/versions/node/v5.1.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/common.js:69:16)
    at installHelper (/Users/Marketing/.nvm/versions/node/v5.1.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/ios.js:55:16)
    at module.exports.header-file.install (/Users/Marketing/.nvm/versions/node/v5.1.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/ios.js:155:13)
    at /Users/Marketing/.nvm/versions/node/v5.1.0/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/PlatformApiPoly.js:654:27
    at Object.ActionStack.process (/Users/Marketing/.nvm/versions/node/v5.1.0/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PlatformApiPoly.addPlugin (/Users/Marketing/.nvm/versions/node/v5.1.0/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/PlatformApiPoly.js:259:20)
    at handleInstall (/Users/Marketing/.nvm/versions/node/v5.1.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:603:6)
    at /Users/Marketing/.nvm/versions/node/v5.1.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:382:28
    at _fulfilled (/Users/Marketing/.nvm/versions/node/v5.1.0/lib/node_modules/cordova/node_modules/q/q.js:787:54)
Error: Uh oh!
"/Users/Marketing/Desktop/foo/foo/mobile_apps/ios_app/foo/cordova/plugins/com.alignace.cordova.plugin.card.reader/src/ios/CardRaderPlugin.h" not found!
```

**Comment by filmerjarred** [comment]
Heyyy, just wondering what the state of this repo is. We've tried to get it building on ios, and after fixing the above issue we're getting mega errors. Not sure if us (which is very well could be), or this repo isn't being maintained?

**Comment by kholmukhamedovme** [comment]
There is another fork of this repo — https://github.com/gamezj/card-reader-phonegap. Maybe its contributors fixed the problems. Anyway I have proprietary plugin that I can send you, of course, if you want.

**Comment by ghost** [comment]
I have a little bit of a problem start the card reader. 

do I use this method to start cardReaderStart()?

or maybe cardReaderStart(cardReadSuccess, cardReadFailure).

i'm using the square card reader.

**Comment by filmerjarred** [comment]
Interesting. Honestly we already have plugin code, we're just chasing a 64bit ios sdk, as apple no longer accepts apps with 32bit libraries

**Comment by gautamgdeft** [comment]
Hello!
I am trying to use this plugin for 3.5 mm jack swipe reader, but it is not showing any response. Can you tell me better way to debug ?

**Comment by filmerjarred** [comment]
We had to go and develop our own sdk for the reader, we had no luck with
this one.

**Comment by KumarSunil007** [comment]
Please find the working plugin  https://github.com/KumarSunil007/phonegap-jack-reader-plugin
